### ISSUE TITLE
add support for SNS

### ISSUE THREAD

**Issue by theburningmonk** [horike37/serverless-apigateway-service-proxy#10]

**Comment by erezrokah** [comment]
I can handle this if no one has started.

Following this can help:
https://www.alexdebrie.com/posts/aws-api-gateway-service-proxy/#creating-the-service-proxy-integration

**Comment by horike37** [comment]
@erezrokah 
Awesome! No one probably has started working on this yet. And you @theburningmonk ?

**Comment by theburningmonk** [comment]
Nope, haven't started, fire away!
