### ISSUE TITLE
add support for setting `AuthorizationType` and `AuthorizerId`

### ISSUE THREAD

**Issue by erezrokah** [horike37/serverless-apigateway-service-proxy#11]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-authorizationtype

**Comment by erezrokah** [comment]
I think I'll have time to implement this later today

**Comment by horike37** [comment]
@erezrokah 
Great! The custom authorizer has already implemented in the framework core so we should be able to re-use it.
Let me know if you have any question.
