### ISSUE TITLE
Docs: avoid using `Fn::Sub` in Readme or specify a plugin is required

### ISSUE THREAD

**Issue by erezrokah** [horike37/serverless-apigateway-service-proxy#28]
See here: https://github.com/horike37/serverless-apigateway-service-proxy/blob/ddb11e91873f8eb206327d00e17127eebff96163/README.md#L297

The serverless framework supports `Fn::Sub` only when using an additional [plugin](https://github.com/santiagocardenas/serverless-cloudformation-sub-variables).

We should either use `Fn::Join` or specify a plugin is required

**Comment by erezrokah** [comment]
Will be fixed in #25

**Comment by theburningmonk** [comment]
Fixed in #25
