### ISSUE TITLE
sls package failed with the latest version of the plugin

### ISSUE THREAD

**Issue by devsatishm** [horike37/serverless-apigateway-service-proxy#57]
Looks like the latest version is broken! When I try to run `sls package` on a service with `serverless-apigateway-service-proxy` as a plugin, I get the following error.

<img width="1045" alt="Screen Shot 2019-12-05 at 4 27 07 PM" src="https://user-images.githubusercontent.com/10748272/70285733-6325e480-177d-11ea-81ab-07fc437cc99f.png">

Post install of the module - `common-tags` explicitly, `sls package` command works as expected.

<img width="626" alt="Screen Shot 2019-12-05 at 4 36 45 PM" src="https://user-images.githubusercontent.com/10748272/70285793-96687380-177d-11ea-8603-315eee735347.png">

**Comment by taylorreece** [comment]
To elaborate, https://github.com/horike37/serverless-apigateway-service-proxy/blob/master/lib/package/dynamodb/compileMethodsToDynamodb.js requires common-tags, but common-tags is not listed as a dependency in package.js.  Should be an easy fix.
