### ISSUE TITLE
Private methods?

### ISSUE THREAD

**Issue by airmonitor** [horike37/serverless-apigateway-service-proxy#59]
Hey,

Will it be possible to add private option in similar way as it is already in sls core?

    events:
      - http:
          method: POST
          path: /metrics
          integration: lambda
          cors: true
          private: true

**Comment by AhmedNourJamalElDin** [comment]
+1

**Comment by horike37** [comment]
@airmonitor 
Hi. Thank you for opening this issune!
That is not supported for now. Would be great if you can work on this.

**Comment by AhmedNourJamalElDin** [comment]
@horike37 
what about this [line ](https://github.com/horike37/serverless-apigateway-service-proxy/blob/d7c710dbc1db7eede00166c0b7866cc4649be9eb/lib/package/sqs/compileMethodsToSqs.js#L20)

**Comment by horike37** [comment]
@AhmedNourJamalElDin 
Yup 👍

**Comment by AhmedNourJamalElDin** [comment]
But it's returning this error: 
```
 child "sqs" fails because ["private" is not allowed]
```

Any help to solve it? I don't think it's hard

**Comment by AhmedNourJamalElDin** [comment]
@horike37  please check this #60

**Comment by AhmedNourJamalElDin** [comment]
@horike37 any update, pls?
